apiVersion: autoscaling/v2beta2 
kind: HorizontalPodAutoscaler
metadata:
  name: memory-autoscale 
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: client-service 
  minReplicas: 1 
  maxReplicas: 10 
  metrics: 
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization 
        averageUtilization: 50
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 1
      policies:
      - type: Percent
        value: 65
        periodSeconds: 1
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
      - type: Pods
        value: 2
        periodSeconds: 5
      - type: Percent
        value: 75
        periodSeconds: 1
      selectPolicy: Max